# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'
  timeoutInMinutes: 10

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Build.SourcesDirectory)\Forge.sln'

- task: VSBuild@1
  displayName: 'Build .NET sln'
  inputs:
    solution: '$(Build.SourcesDirectory)\Forge.sln'
    platform: 'Any CPU'
    configuration: Release

- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    testAssemblyVer2: | 
      $(Build.SourcesDirectory)\Forge.TreeWalker.UnitTests\obj\Release\Forge.TreeWalker.UnitTests.dll
    runInParallel: True

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'
    configuration: 'Release'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'ForgeArtifacts'
    allowPackageConflicts: true