trigger:
- master

pool:
  vmImage: 'windows-2019'
  timeoutInMinutes: 10

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Build.SourcesDirectory)\Forge.sln'

- task: VSBuild@1
  displayName: 'Build .NET sln'
  inputs:
    solution: '$(Build.SourcesDirectory)\Forge.sln'
    platform: 'Any CPU'
    configuration: Release

- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    testAssemblyVer2: | 
      $(Build.SourcesDirectory)\Forge.TreeWalker.UnitTests\obj\Release\Forge.TreeWalker.UnitTests.dll
    runInParallel: True

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'
    configuration: 'Release'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'Forge ESRP CodeSign2'
    FolderPath: '$(Build.SourcesDirectory)'
    Pattern: 'Forge.TreeWalker.dll'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [ 
         {
             "keyCode": "CP-401405",
             "operationSetCode": "NuGetSign",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-401405",
             "operationSetCode": "NuGetVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: NuGetCommand@2
  displayName: 'NuGet push AzureArtifacts'
  inputs:
    command: push
    publishVstsFeed: 'ForgeArtifacts'
    allowPackageConflicts: true